### ISSUE TITLE
automate org/team membership

### ISSUE THREAD

**Issue by ilrudie** [k8sgateway/community#24]
https://docs.prow.k8s.io/docs/components/cli-tools/peribolos/ looks like it might be a good way to handle this, open to suggestions though

**Comment by ilrudie** [comment]
https://youtu.be/te3Xj2zr1Co?si=mNffajzTC1Z5AjLJ is a kubecon talk on the subject

**Comment by danehans** [comment]
I'd like to see the project follow https://www.kubernetes.dev/docs/guide/owners/.

**Comment by ilrudie** [comment]
> I'd like to see the project follow https://www.kubernetes.dev/docs/guide/owners/.

Can this be achieved without adopting prow?

**Comment by ilrudie** [comment]
Also, do we want the owners files to managed by hand, or automation? If by hand and we elide the automation then we could close this out potentially. If we want automation which updates the owners files like kube has then we would still need _something_ like this, potentially as a prerequisite

**Comment by ilrudie** [comment]
Also needs considering, are we looking to sub-divide the "controller" repo into multiple areas of responsibility (aside from current status, which is just docs and everything else) to be more specialized or do we expect it stick with "controller-maintainer" (and potentially reviewer/approver) as role(s) which own ~the whole repo?
