### ISSUE TITLE
test vote 

### ISSUE THREAD

**Issue by linsun** [k8sgateway/community#39]

**Comment by ilrudie** [comment]
I am not against this, just trying a different option!

**Comment by linsun** [comment]
thanks @ilrudie i think it works :) and recorded our votes well :)

**Comment by linsun** [comment]
> Votes can only be checked once a day.

I think that is a limitation with the bot - we have to live with it in cncf toc too.

**Comment by linsun** [comment]
closing this issue, as the bot testing is complete - it can kick off a vote and record vote results whenever requested (rate limit is 1 per day).

**Comment by ilrudie** [comment]
> thanks @ilrudie i think it works :) and recorded our votes well :)

yeah! I think this will help with the issues around changing up/down votes after the fact! Also if we keep eligible-voters groomed correctly I think anyone can up/down vote it but the bot will figure it out correctly?
